import { findRoute } from '../railwayRouting';
import { getRouteVisualData } from '../tripCalculator';

/**
 * A utility class for the Bot to process a raw trip intent (start and end stations)
 * into a fully structured payload containing routing segments, accurate distance,
 * and SVG paths, ready to be sent to the RailRound Cloudflare API.
 */
export class BotTripWorker {
    private railwayData: any;
    private geoData: any;

    /**
     * @param railwayData The structured railway data generated by BotDataBuilder
     * @param geoData The structured GeoJSON data generated by BotDataBuilder
     */
    constructor(railwayData: any, geoData: any) {
        if (!railwayData || !geoData) {
            throw new Error("BotTripWorker requires initialized railwayData and geoData.");
        }
        this.railwayData = railwayData;
        this.geoData = geoData;
    }

    /**
     * Calculates a route between two stations and prepares the API payload.
     *
     * @param title Custom title for the trip
     * @param startLineKey The line key of the start station (e.g., 'JR East:Yamanote Line')
     * @param startStId The ID of the start station
     * @param endLineKey The line key of the end station
     * @param endStId The ID of the end station
     * @param date Optional date string (YYYY-MM-DD)
     * @returns A payload object ready to be sent to POST /api/qqbot/record
     */
    public processTrip(
        title: string,
        startLineKey: string,
        startStId: string,
        endLineKey: string,
        endStId: string,
        date?: string
    ) {
        // 1. Calculate the route
        const routeResult = findRoute(
            startLineKey,
            startStId,
            endLineKey,
            endStId,
            this.railwayData,
            6 // Max transfers
        );

        if (routeResult.error || !routeResult.segments) {
            throw new Error(`Routing failed: ${routeResult.error}`);
        }

        const segments = routeResult.segments;

        // 2. Extract visual data (distance and geographic paths)
        // We pass an empty object {} for segmentGeometries cache, it will compute on the fly
        const visualData = getRouteVisualData(segments, {}, this.railwayData, this.geoData);

        // 3. Combine visual paths into a single SVG 'd' string for the Badge renderer
        const svgPoints = visualData.visualPaths.map((vp: any) => vp.path).join(" ");

        // 4. Extract unique lines and stations for the API payload metadata
        const lineNames = new Set<string>();
        const stationNames = new Set<string>();

        segments.forEach((seg: any) => {
            const lineName = seg.lineKey.split(':').pop();
            if (lineName) lineNames.add(lineName);

            // Just grab start and end of segment for simplicity in summary
            const line = this.railwayData[seg.lineKey];
            if (line) {
                const s1 = line.stations.find((s: any) => s.id === seg.fromId);
                const s2 = line.stations.find((s: any) => s.id === seg.toId);
                if (s1) stationNames.add(s1.name_ja);
                if (s2) stationNames.add(s2.name_ja);
            }
        });

        // 5. Construct the final payload for /api/qqbot/record
        return {
            title: title || Array.from(lineNames).join(' → '),
            date: date || new Date().toISOString().split('T')[0],
            distance: visualData.totalDist,
            lines: Array.from(lineNames),
            stations: Array.from(stationNames),
            segments: segments,
            svg_points: svgPoints
        };
    }
}
