import { computeLoopVia } from '../core/railwayRouting';
import type { RailwayLine, RailwayMap, TripSegment } from '../store';

export type NetworkEventType =
  | 'reverse_operation'
  | 'formation_operation'
  | 'service_class_switch'
  | 'transfer'
  | string;

export type TransferMode = 'in_vehicle_through' | 'alight_transfer';

export interface NetworkSubSegment {
  id: string;
  fromStationIndex: number;
  toStationIndex: number;
  lineAlias?: string;
  serviceLevel?: string;
  destination?: string;
}

export interface NetworkMetaEvent {
  id?: string;
  type: NetworkEventType;
  stationIndex?: number;
  transferMode?: TransferMode;
  requiresTransfer?: boolean;
  fromSegmentId?: string;
  toSegmentId?: string;
  displayLabel?: string;
  [key: string]: any;
}

export interface DirectionBucket {
  subSegments?: NetworkSubSegment[];
  events?: NetworkMetaEvent[];
  systems?: string[];
  [key: string]: any;
}

export interface DisplaySegment {
  id: string;
  title: string;
  lineAlias: string;
  serviceLevel?: string;
  destination?: string;
  stationIndices: number[];
  stationIds: string[];
  stationNames: string[];
  fromStationId: string;
  toStationId: string;
}

export interface DisplaySegmentBoundary {
  leftSegmentId: string;
  rightSegmentId: string;
  stationIndex: number;
  stationName: string;
  events: (NetworkMetaEvent & {
    isAutoGenerated?: boolean;
    transferMode?: TransferMode;
    requiresTransfer?: boolean;
  })[];
}

export interface DisplayModel {
  direction: 'up' | 'down';
  segments: DisplaySegment[];
  boundaries: DisplaySegmentBoundary[];
  autoGeneratedTransferCount: number;
}

const getLineAliasFallback = (lineKey: string) =>
  lineKey.includes(':') ? lineKey.split(':').slice(1).join(':') : lineKey;

const toFiniteInt = (value: any): number | null => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return null;
  return Math.trunc(parsed);
};

const uniqueStrings = (arr: any[]) => {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const item of arr || []) {
    if (typeof item !== 'string') continue;
    const trimmed = item.trim();
    if (!trimmed || seen.has(trimmed)) continue;
    seen.add(trimmed);
    out.push(trimmed);
  }
  return out;
};

const normalizeBucket = (bucket: any): DirectionBucket => {
  if (!bucket || typeof bucket !== 'object') return {};
  const subSegmentsRaw = Array.isArray(bucket.subSegments) ? bucket.subSegments : [];
  const eventsRaw = Array.isArray(bucket.events) ? bucket.events : [];
  return {
    ...bucket,
    systems: uniqueStrings(Array.isArray(bucket.systems) ? bucket.systems : []),
    subSegments: subSegmentsRaw
      .map((seg: any, idx: number) => {
        const fromStationIndex = toFiniteInt(seg?.fromStationIndex);
        const toStationIndex = toFiniteInt(seg?.toStationIndex);
        if (fromStationIndex === null || toStationIndex === null) return null;
        const id =
          typeof seg?.id === 'string' && seg.id.trim()
            ? seg.id.trim()
            : `sub_segment_${idx}`;
        return {
          id,
          fromStationIndex,
          toStationIndex,
          lineAlias: typeof seg?.lineAlias === 'string' ? seg.lineAlias : undefined,
          serviceLevel:
            typeof seg?.serviceLevel === 'string' ? seg.serviceLevel : undefined,
          destination:
            typeof seg?.destination === 'string' ? seg.destination : undefined,
        } as NetworkSubSegment;
      })
      .filter(Boolean) as NetworkSubSegment[],
    events: eventsRaw
      .map((event: any, idx: number) => {
        if (!event || typeof event !== 'object') return null;
        const type =
          typeof event.type === 'string'
            ? event.type
            : typeof event.eventType === 'string'
              ? event.eventType
              : null;
        if (!type) return null;
        const stationIndex = toFiniteInt(event.stationIndex);
        const normalizedEvent: NetworkMetaEvent = {
          ...event,
          id:
            typeof event.id === 'string' && event.id.trim()
              ? event.id.trim()
              : `event_${idx}`,
          type,
          ...(stationIndex !== null ? { stationIndex } : {}),
        };
        if (
          normalizedEvent.type === 'reverse_operation' ||
          normalizedEvent.type === 'formation_operation' ||
          normalizedEvent.type === 'service_class_switch'
        ) {
          normalizedEvent.requiresTransfer = false;
        }
        return normalizedEvent;
      })
      .filter(Boolean) as NetworkMetaEvent[],
  };
};

const getDirectionBucket = (line: RailwayLine, direction: 'up' | 'down') => {
  const rawMeta = (line.meta as any)?.networkMeta;
  if (!rawMeta || typeof rawMeta !== 'object') return null;
  if (rawMeta.byDirection?.[direction]) {
    return normalizeBucket(rawMeta.byDirection[direction]);
  }
  if (rawMeta.common) {
    return normalizeBucket(rawMeta.common);
  }
  if (rawMeta.subSegments || rawMeta.events || rawMeta.systems) {
    return normalizeBucket(rawMeta);
  }
  return null;
};

const inferTransferMode = (
  event: NetworkMetaEvent,
  left: DisplaySegment,
  right: DisplaySegment,
): TransferMode => {
  if (event.transferMode === 'in_vehicle_through' || event.transferMode === 'alight_transfer') {
    return event.transferMode;
  }
  const sameAlias = (left.lineAlias || '').trim() === (right.lineAlias || '').trim();
  const sameServiceLevel = (left.serviceLevel || '').trim() === (right.serviceLevel || '').trim();
  const sameDestination = (left.destination || '').trim() === (right.destination || '').trim();
  if (sameAlias && (sameServiceLevel || sameDestination)) {
    return 'in_vehicle_through';
  }
  return 'alight_transfer';
};

const resolveDirection = (
  segment: TripSegment,
  line: RailwayLine,
  railwayData: RailwayMap,
): 'up' | 'down' => {
  // Keep parity with geo.worker getDirectionForSegment behavior.
  if (line.meta?.isLoop) {
    if (segment.loopVia === 'up' || segment.loopVia === 'down') return segment.loopVia;
    const via = computeLoopVia(railwayData, segment.lineKey, segment.fromId, segment.toId);
    return via === 'down' ? 'down' : 'up';
  }
  if (segment.direction === 'up' || segment.direction === 'down') return segment.direction;
  const fromIdx = line.stations.findIndex((s) => s.id === segment.fromId);
  const toIdx = line.stations.findIndex((s) => s.id === segment.toId);
  if (fromIdx === -1 || toIdx === -1) return 'up';
  return fromIdx <= toIdx ? 'up' : 'down';
};

const buildStationIndexPath = (
  count: number,
  fromIdx: number,
  toIdx: number,
  isLoop: boolean,
  direction: 'up' | 'down',
) => {
  if (fromIdx < 0 || toIdx < 0 || fromIdx >= count || toIdx >= count) return [];
  if (!isLoop) {
    const out: number[] = [];
    const step = fromIdx <= toIdx ? 1 : -1;
    for (let i = fromIdx; step === 1 ? i <= toIdx : i >= toIdx; i += step) {
      out.push(i);
    }
    return out;
  }
  const out: number[] = [];
  const dir = direction === 'up' ? 1 : -1;
  let current = fromIdx;
  let guard = 0;
  while (guard < count + 2) {
    out.push(current);
    if (current === toIdx) break;
    current = (current + dir + count) % count;
    guard += 1;
  }
  return out;
};

const buildFallbackSegment = (
  line: RailwayLine,
  lineKey: string,
  pathIndices: number[],
): DisplaySegment | null => {
  if (pathIndices.length < 2) return null;
  const stationIndices = [...pathIndices];
  const stationIds = stationIndices.map((idx) => line.stations[idx]?.id).filter(Boolean);
  const stationNames = stationIndices
    .map((idx) => line.stations[idx]?.name_ja)
    .filter(Boolean) as string[];
  if (stationIds.length < 2 || stationNames.length < 2) return null;
  const lineAlias = getLineAliasFallback(lineKey);
  return {
    id: `fallback_${lineKey}_${stationIds[0]}_${stationIds[stationIds.length - 1]}`,
    title: lineAlias,
    lineAlias,
    stationIndices,
    stationIds: stationIds as string[],
    stationNames,
    fromStationId: stationIds[0] as string,
    toStationId: stationIds[stationIds.length - 1] as string,
  };
};

export const buildNetworkDisplayModel = (
  segment: TripSegment,
  railwayData: RailwayMap,
): DisplayModel | null => {
  const line = railwayData[segment.lineKey];
  if (!line || !segment.fromId || !segment.toId) return null;

  const fromIdx = line.stations.findIndex((s) => s.id === segment.fromId);
  const toIdx = line.stations.findIndex((s) => s.id === segment.toId);
  if (fromIdx === -1 || toIdx === -1) return null;

  const direction = resolveDirection(segment, line, railwayData);
  const pathIndices = buildStationIndexPath(
    line.stations.length,
    fromIdx,
    toIdx,
    !!line.meta?.isLoop,
    direction,
  );
  if (pathIndices.length < 2) return null;

  const bucket = getDirectionBucket(line, direction);
  const subSegments = bucket?.subSegments || [];
  const events = bucket?.events || [];
  const pathPos = new Map<number, number>();
  pathIndices.forEach((idx, pos) => {
    if (!pathPos.has(idx)) pathPos.set(idx, pos);
  });

  const ranges = subSegments
    .map((sub) => {
      const posA = pathPos.get(sub.fromStationIndex);
      const posB = pathPos.get(sub.toStationIndex);
      if (posA === undefined || posB === undefined) return null;
      const start = Math.min(posA, posB);
      const end = Math.max(posA, posB);
      if (start === end) return null;
      return { start, end, sub };
    })
    .filter(Boolean) as { start: number; end: number; sub: NetworkSubSegment }[];

  let displaySegments: DisplaySegment[] = [];

  if (ranges.length > 0) {
    const breakpoints = new Set<number>([0, pathIndices.length - 1]);
    for (const range of ranges) {
      breakpoints.add(range.start);
      breakpoints.add(range.end);
    }
    const sortedPoints = [...breakpoints].sort((a, b) => a - b);
    for (let i = 0; i < sortedPoints.length - 1; i += 1) {
      const start = sortedPoints[i];
      const end = sortedPoints[i + 1];
      if (end <= start) continue;
      const owner =
        ranges.find((r) => r.start <= start && r.end >= end)?.sub || null;
      const stationIndices = pathIndices.slice(start, end + 1);
      const stationIds = stationIndices
        .map((idx) => line.stations[idx]?.id)
        .filter(Boolean) as string[];
      const stationNames = stationIndices
        .map((idx) => line.stations[idx]?.name_ja)
        .filter(Boolean) as string[];
      if (stationIds.length < 2) continue;
      const lineAlias = owner?.lineAlias || getLineAliasFallback(segment.lineKey);
      const title = owner?.serviceLevel
        ? `${lineAlias} (${owner.serviceLevel})`
        : lineAlias;
      displaySegments.push({
        id:
          owner?.id ||
          `generated_${segment.lineKey}_${stationIds[0]}_${stationIds[stationIds.length - 1]}_${i}`,
        title,
        lineAlias,
        serviceLevel: owner?.serviceLevel,
        destination: owner?.destination,
        stationIndices,
        stationIds,
        stationNames,
        fromStationId: stationIds[0],
        toStationId: stationIds[stationIds.length - 1],
      });
    }
  }

  if (displaySegments.length === 0) {
    const fallback = buildFallbackSegment(line, segment.lineKey, pathIndices);
    if (!fallback) return null;
    displaySegments = [fallback];
  }

  const boundaries: DisplaySegmentBoundary[] = [];
  let autoGeneratedTransferCount = 0;

  for (let i = 0; i < displaySegments.length - 1; i += 1) {
    const left = displaySegments[i];
    const right = displaySegments[i + 1];
    const stationIndex = left.stationIndices[left.stationIndices.length - 1];
    const stationName = line.stations[stationIndex]?.name_ja || '';

    const matched = events.filter((event) => {
      if (event.stationIndex !== undefined && event.stationIndex !== stationIndex) {
        return false;
      }
      if (event.fromSegmentId && event.fromSegmentId !== left.id) return false;
      if (event.toSegmentId && event.toSegmentId !== right.id) return false;
      return true;
    });

    const hasTransfer = matched.some((event) => event.type === 'transfer');
    const mergedEvents = matched.map((event) => {
      if (event.type !== 'transfer') return event;
      const transferMode = inferTransferMode(event, left, right);
      return {
        ...event,
        transferMode,
        requiresTransfer:
          typeof event.requiresTransfer === 'boolean'
            ? event.requiresTransfer
            : transferMode === 'alight_transfer',
      };
    });

    if (!hasTransfer) {
      autoGeneratedTransferCount += 1;
      mergedEvents.push({
        id: `auto_transfer_${left.id}_${right.id}`,
        type: 'transfer',
        stationIndex,
        transferMode: 'in_vehicle_through',
        requiresTransfer: false,
        fromSegmentId: left.id,
        toSegmentId: right.id,
        isAutoGenerated: true,
      });
    }

    boundaries.push({
      leftSegmentId: left.id,
      rightSegmentId: right.id,
      stationIndex,
      stationName,
      events: mergedEvents,
    });
  }

  return {
    direction,
    segments: displaySegments,
    boundaries,
    autoGeneratedTransferCount,
  };
};

export const getLineSystems = (line: RailwayLine): string[] => {
  const rawMeta = (line.meta as any)?.networkMeta;
  if (!rawMeta || typeof rawMeta !== 'object') return [];
  const pool: string[] = [];
  if (Array.isArray(rawMeta.systems)) pool.push(...rawMeta.systems);
  if (Array.isArray(rawMeta.common?.systems)) pool.push(...rawMeta.common.systems);
  if (Array.isArray(rawMeta.byDirection?.up?.systems)) {
    pool.push(...rawMeta.byDirection.up.systems);
  }
  if (Array.isArray(rawMeta.byDirection?.down?.systems)) {
    pool.push(...rawMeta.byDirection.down.systems);
  }
  return uniqueStrings(pool);
};
